name: test

on:
  schedule:
    - cron: "0 8 * * 2"
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Pester, UncommonSense.Hap -Scope CurrentUser

      - name: Run Pester tests
        shell: pwsh
        run: Invoke-Pester -Output Detailed
